# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x15\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty2D\n\x07Manager\x12 \n\x04sell\x12\x08.Product\x1a\x0e.StringMessage\x12\x17\n\x03\x62uy\x12\x06.Empty\x1a\x08.Productb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRINGMESSAGE']._serialized_start=17
  _globals['_STRINGMESSAGE']._serialized_end=47
  _globals['_PRODUCT']._serialized_start=49
  _globals['_PRODUCT']._serialized_end=70
  _globals['_EMPTY']._serialized_start=72
  _globals['_EMPTY']._serialized_end=79
  _globals['_MANAGER']._serialized_start=81
  _globals['_MANAGER']._serialized_end=149
# @@protoc_insertion_point(module_scope)
