# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderManagement.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15orderManagement.proto\x12\x0forder_managemet\"[\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"_\n\x10\x43ombinedShipment\x12\x13\n\x0bshipment_id\x18\x01 \x01(\t\x12&\n\x06orders\x18\x02 \x03(\x0b\x32\x16.order_managemet.Order\x12\x0e\n\x06status\x18\x03 \x01(\t2\xb0\x02\n\x0cOrderManager\x12\x42\n\x08\x61\x64\x64Order\x12\x16.order_managemet.Order\x1a\x1e.order_managemet.StringMessage\x12\x42\n\x08getOrder\x12\x1e.order_managemet.StringMessage\x1a\x16.order_managemet.Order\x12H\n\x0csearchOrders\x12\x1e.order_managemet.StringMessage\x1a\x16.order_managemet.Order0\x01\x12N\n\rprocessOrders\x12\x16.order_managemet.Order\x1a!.order_managemet.CombinedShipment(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderManagement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=42
  _globals['_ORDER']._serialized_end=133
  _globals['_STRINGMESSAGE']._serialized_start=135
  _globals['_STRINGMESSAGE']._serialized_end=165
  _globals['_COMBINEDSHIPMENT']._serialized_start=167
  _globals['_COMBINEDSHIPMENT']._serialized_end=262
  _globals['_ORDERMANAGER']._serialized_start=265
  _globals['_ORDERMANAGER']._serialized_end=569
# @@protoc_insertion_point(module_scope)
