# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tgenerated\"\x1e\n\x07Product\x12\x13\n\x0bid_articolo\x18\x01 \x01(\x03\"\x07\n\x05\x45mpty2p\n\x07Service\x12\x31\n\x07Preleva\x12\x10.generated.Empty\x1a\x12.generated.Product\"\x00\x12\x32\n\x08\x44\x65posita\x12\x12.generated.Product\x1a\x10.generated.Empty\"\x00\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_PRODUCT']._serialized_start=28
  _globals['_PRODUCT']._serialized_end=58
  _globals['_EMPTY']._serialized_start=60
  _globals['_EMPTY']._serialized_end=67
  _globals['_SERVICE']._serialized_start=69
  _globals['_SERVICE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
