# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\x12\tmagazzino\"&\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07product\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xa6\x01\n\x07Manager\x12/\n\x07preleva\x12\x10.magazzino.Empty\x1a\x12.magazzino.Product\x12\x38\n\x08\x64\x65posita\x12\x12.magazzino.Product\x1a\x18.magazzino.StringMessage\x12\x30\n\x06svuota\x12\x10.magazzino.Empty\x1a\x12.magazzino.Product0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=28
  _globals['_PRODUCT']._serialized_end=66
  _globals['_STRINGMESSAGE']._serialized_start=68
  _globals['_STRINGMESSAGE']._serialized_end=98
  _globals['_EMPTY']._serialized_start=100
  _globals['_EMPTY']._serialized_end=107
  _globals['_MANAGER']._serialized_start=110
  _globals['_MANAGER']._serialized_end=276
# @@protoc_insertion_point(module_scope)
