# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07sensors\"(\n\x06Sensor\x12\x0b\n\x03_id\x18\x01 \x01(\x03\x12\x11\n\tdata_type\x18\x02 \x01(\t\"3\n\x0bMeanRequest\x12\x11\n\tsensor_id\x18\x01 \x01(\x03\x12\x11\n\tdata_type\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2s\n\x07Service\x12/\n\ngetSensors\x12\x0e.sensors.Empty\x1a\x0f.sensors.Sensor0\x01\x12\x37\n\x07getMean\x12\x14.sensors.MeanRequest\x1a\x16.sensors.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSOR']._serialized_start=26
  _globals['_SENSOR']._serialized_end=66
  _globals['_MEANREQUEST']._serialized_start=68
  _globals['_MEANREQUEST']._serialized_end=119
  _globals['_STRINGMESSAGE']._serialized_start=121
  _globals['_STRINGMESSAGE']._serialized_end=151
  _globals['_EMPTY']._serialized_start=153
  _globals['_EMPTY']._serialized_end=160
  _globals['_SERVICE']._serialized_start=162
  _globals['_SERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
