// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: magazzino.proto

package dispatcher;

public interface ArticoloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.Articolo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 valore = 1;</code>
   * @return The valore.
   */
  long getValore();
}
