// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: magazzino.proto

package dispatcher;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dispatcher.Empty)
    com.google.protobuf.MessageOrBuilder {
}
