# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bookingService.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ookingService.proto\x12\tgenerated\"\x07\n\x05\x45mpty\"=\n\x0bReservation\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0e\n\x06people\x18\x02 \x01(\x05\x12\x10\n\x08timeSlot\x18\x03 \x01(\t\"\x1e\n\rStatsResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x32\x94\x01\n\x0e\x42ookingManager\x12\x42\n\x14GetTotalReservations\x12\x10.generated.Empty\x1a\x18.generated.StatsResponse\x12>\n\x12GetLastReservation\x12\x10.generated.Empty\x1a\x16.generated.ReservationB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bookingService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_EMPTY']._serialized_start=35
  _globals['_EMPTY']._serialized_end=42
  _globals['_RESERVATION']._serialized_start=44
  _globals['_RESERVATION']._serialized_end=105
  _globals['_STATSRESPONSE']._serialized_start=107
  _globals['_STATSRESPONSE']._serialized_end=137
  _globals['_BOOKINGMANAGER']._serialized_start=140
  _globals['_BOOKINGMANAGER']._serialized_end=288
# @@protoc_insertion_point(module_scope)
